# ==========================================================================
# CRE PROJECT SETTINGS FILE
# ==========================================================================
# Project-specific settings for CRE CLI targets.
# Each target defines cre-cli, account, and rpcs groups.
#
# Example custom target:
# my-target:
#   account:
#     workflow-owner-address: "0x123..."            # Optional: Owner wallet/MSIG address (used for --unsigned transactions)
#   rpcs:
#     - chain-name: ethereum-mainnet                # Required: Chain RPC endpoints
#       url: "https://mainnet.infura.io/v3/KEY"

# ==========================================================================
staging-settings:
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://ethereum-sepolia-rpc.publicnode.com
    - chain-name: ethereum-testnet-sepolia-base-1
      url: https://sepolia.base.org
    - chain-name: ethereum-testnet-sepolia-arbitrum-1
      url: https://sepolia-rollup.arbitrum.io/rpc
    - chain-name: ethereum-testnet-sepolia-optimism-1
      url: https://sepolia.optimism.io

# ==========================================================================
production-settings:
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://ethereum-sepolia-rpc.publicnode.com
    - chain-name: ethereum-mainnet
      url: https://mainnet.infura.io/v3/<YOUR-PROJECT-ID>
    - chain-name: ethereum-mainnet-base-1
      url: https://mainnet.base.org
    - chain-name: ethereum-mainnet-arbitrum-1
      url: https://arb1.arbitrum.io/rpc
    - chain-name: ethereum-mainnet-optimism-1
      url: https://mainnet.optimism.io
